title: Sangam Kumar
description: >
  
permalink: ':title/'
site-twitter: meetsangamcse

author: Sangam Kumar
author-img: sangam.jpg
about-author: Senior undergraduate | Pythonista | Learner
social-twitter: meetsangamcse
social-facebook: meetsangamcse
social-github: sangamcse
social-linkedin: sangamcse
social-email: meetsangamcse@gmail.com

subscribe_rss: /feed.xml

discus-identifier: meetsangamcse 

# Tracker
analytics: UA-118439543-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
